### ISSUE TITLE
Website doesn’t load anymore.

### ISSUE THREAD

**Issue by tapir132** [25Karma/25Karma#15]
I assume that this might have something to do with Hypixel disabling the friends api, but for a couple of days now the website doesn’t load when you search for a player.

**Comment by Yan-Jobs** [comment]
The private 25karma api is dead, I’m setting up a mirror with a working api

**Comment by Gloryness** [comment]
This is due to the recent change in the Hypixel API. The Developer of 25karma cannot be blamed for this because when setting up the friends API you wouldn't really expect for the endpoint to suddenly be removed, which is what Hypixel has done.

[[Public API] Removal of the friends endpoint](https://hypixel.net/threads/public-api-removal-of-the-friends-endpoint.5245947/page-2#post-37601615)

**Comment by Yan-Jobs** [comment]
> This is due to the recent change in the Hypixel API. The Developer of 25karma cannot be blamed for this because when setting up the friends API you wouldn't really expect for the endpoint to suddenly be removed, which is what Hypixel has done.
> 
> [[Public API] Removal of the friends endpoint](https://hypixel.net/threads/public-api-removal-of-the-friends-endpoint.5245947/page-2#post-37601615)

AHHHHHH so a PR will maybe fix this, Ill try to fix it then.
Thanks for showing that forum post!

**Comment by amosyu2000** [comment]
Hey y'all. Got around to fixing the issue where my API hangs when waiting for the friends endpoint from Hypixel. I also removed all references to friends from my website. Thanks for your patience and your willingness to help.
